### PR TITLE
Support of Lunar 1.x

### PR DESCRIPTION
**Pull request by lguichard**
This PR is a draft to support Lunar 1.x version.

TODO : 
- [x]  Support Docker
- [x]  Lando support
- [x]  Meilisearch support
- [x]  Meilisearch UI
- [x]  Redis
- [x]  Mailhog
- [x]  Livewire 3 support 
- [x]  Fix database seeder
- [x]  Fix automatic install 
- [x]  Remove webpack and add Vite
- [x]  Update dependencies
- [x]  Add shipping add-on and remove old logic 
- [x] Support Laravel 10.x
- [x]  Cleaning project
- [x]  Fix Livewire 3 issues in storefront
- [x]  Use wire:navigate
- [x]  Documentation

### CODE REVIEW

**Comment by eugenefvdm** [comment]
@lguichard I'm happy to tackle some of this?

> Livewire 3 support
> Remove webpack and add Vite
> Update dependencies

I have some confidence in getting the work done because of some work I have done before:

- Used `php artisan livewire:upgrade` and all seemed good, I selected `yes` for every single question including non default questions.
- I've also shifted 0.8 to 1.x and this seemed to work perfectly
- Used free Shift to do webpack (but this is easy with copy/paste of fresh Laravel)
- Dependency updates doesn't seems that hard? Not sure what I'm missing here.

The only caveat so far I have found after all this work is that the ShippingManifest has an issue so not entirely sure if I should do all this work and hand over a complex ShippingManifest issue (which I couldn't solve).

**Comment by lguichard** [comment]
@eugenefvdm Thank you so much for your comprehensive informations that will help me.

I also convert a Lunar project to L10, i used same steps that you used

**Comment by alecritson** [comment]
Happy to of course also help on this. 

With regard to the shipping issue I think that since 1.0 has the shipping tables add-on available it would make more sense to strip the existing logic in favour of using it.

This should mean the bulk of work needed would be to set up new shipping seeders and register the add-on. 

Happy to take a look or happy for someone else too if they feel happy with the approach.

**Comment by alecritson** [comment]
@lguichard I've pushed a commit which should hopefully take care of the shipping seeders, for now it just adds UK, Europe and US shipping zones and prices. ✌️

**Comment by lguichard** [comment]
> @lguichard I've pushed a commit which should hopefully take care of the shipping seeders, for now it just adds UK, Europe and US shipping zones and prices. ✌️

Thx ! 

Now we have to ProductVariant generation & some tweaks

**Comment by webpatser** [comment]
I just tried this on a fresh v1 install, but there is something with the Carts that is broken.

I will try to hunt this down if you are not already on the case :-)

**Comment by dotmbf** [comment]
didnt know this existed, been toying with it a lot myself.

as i read the documentation of Livewire, is `'legacy_model_binding' => true` really the "correct" fix for the model binding in this case? it seems to me that it's something that they expect to remove in future updates/releases (maybe 4.x, but who knows?)

**Comment by ezequiel9** [comment]
Are you guys merging this anytime soon? I am about to start a project and would be great to start with 1.x . Thank you very much for your hard work on this.

**Review by alecritson — APPROVED** [review]

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
